//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTeknoKurEntities : DbContext
    {
        public DbTeknoKurEntities()
            : base("name=DbTeknoKurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblKategoriler> TblKategoriler { get; set; }
        public virtual DbSet<TblMarka> TblMarka { get; set; }
        public virtual DbSet<TblUrun> TblUrun { get; set; }
        public virtual DbSet<TblUyeKisi> TblUyeKisi { get; set; }
        public virtual DbSet<TblUye> TblUye { get; set; }
        public virtual DbSet<TblKisiAdres> TblKisiAdres { get; set; }
        public virtual DbSet<TblKisiTelefon> TblKisiTelefon { get; set; }
        public virtual DbSet<TblFavori> TblFavori { get; set; }
        public virtual DbSet<VwKisiAdresTelefon> VwKisiAdresTelefon { get; set; }
        public virtual DbSet<TblSepet> TblSepet { get; set; }
        public virtual DbSet<TblSiteAyarlar> TblSiteAyarlar { get; set; }
        public virtual DbSet<TblSiparis> TblSiparis { get; set; }
        public virtual DbSet<TblSiparisDetay> TblSiparisDetay { get; set; }
        public virtual DbSet<VwSiparisUrun> VwSiparisUrun { get; set; }
        public virtual DbSet<TblYorum> TblYorum { get; set; }
        public virtual DbSet<VwUyeKisi> VwUyeKisi { get; set; }
    }
}
