//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFavori
    {
        public int FavoriId { get; set; }
        public int UyeId { get; set; }
        public int UrunId { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public Nullable<bool> Silik { get; set; }
    
        public virtual TblUrun TblUrun { get; set; }
        public virtual TblUye TblUye { get; set; }
    }
}
