//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKisiAdres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKisiAdres()
        {
            this.TblSiparis = new HashSet<TblSiparis>();
        }
    
        public int AdresId { get; set; }
        public int KisiId { get; set; }
        public string AdresBaslik { get; set; }
        public string AdresUlke { get; set; }
        public string AdresIl { get; set; }
        public string AdresIlce { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> Varsayilan { get; set; }
        public Nullable<bool> FaturaAdresi { get; set; }
        public Nullable<int> EkleyenUyeId { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<bool> Silik { get; set; }
        public Nullable<int> SilenUyeId { get; set; }
        public Nullable<System.DateTime> SilmeTarihi { get; set; }
        public Nullable<int> GuncelleyenUyeId { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
    
        public virtual TblUyeKisi TblUyeKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSiparis> TblSiparis { get; set; }
    }
}
