//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKisiTelefon
    {
        public int TelefonId { get; set; }
        public int KisiId { get; set; }
        public string TelefonNumarasi { get; set; }
        public Nullable<bool> Varsayilan { get; set; }
        public Nullable<int> EkleyenUyeId { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<bool> Silik { get; set; }
        public Nullable<int> SilenUyeId { get; set; }
        public Nullable<System.DateTime> SilmeTarihi { get; set; }
        public Nullable<int> GuncelleyenUyeId { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
    
        public virtual TblUyeKisi TblUyeKisi { get; set; }
    }
}
