//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMarka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMarka()
        {
            this.TblUrun = new HashSet<TblUrun>();
        }
    
        public int MarkaId { get; set; }
        public string MarkaAdi { get; set; }
        public string MarkaSeo { get; set; }
        public Nullable<int> EkleyenUyeId { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<bool> Silik { get; set; }
        public Nullable<int> SilenUyeId { get; set; }
        public Nullable<System.DateTime> SilmeTarihi { get; set; }
        public Nullable<int> GuncelleyenUyeId { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrun> TblUrun { get; set; }
    }
}
