//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSiteAyarlar
    {
        public int Id { get; set; }
        public string SiteBaslik { get; set; }
        public bool SiteAcik { get; set; }
        public string MetaTaglari { get; set; }
        public string AnahtarKelimeler { get; set; }
        public decimal StandartHizmetBedeli { get; set; }
    }
}
