//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSiparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSiparis()
        {
            this.TblSiparisDetay = new HashSet<TblSiparisDetay>();
        }
    
        public int SiparisId { get; set; }
        public int UyeId { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public decimal ToplamTutar { get; set; }
        public bool OdemeDurumu { get; set; }
        public Nullable<int> AdresId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSiparisDetay> TblSiparisDetay { get; set; }
        public virtual TblUye TblUye { get; set; }
        public virtual TblKisiAdres TblKisiAdres { get; set; }
    }
}
