//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUrun()
        {
            this.TblFavori = new HashSet<TblFavori>();
            this.TblSepet = new HashSet<TblSepet>();
            this.TblSiparisDetay = new HashSet<TblSiparisDetay>();
            this.TblYorum = new HashSet<TblYorum>();
        }
    
        public int UrunId { get; set; }
        public int KategoriId { get; set; }
        public int MarkaId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKodu { get; set; }
        public string UrunResimUrl { get; set; }
        public string UrunSeo { get; set; }
        public string UrunTaglar { get; set; }
        public decimal UrunFiyat { get; set; }
        public string UrunAciklama { get; set; }
        public string TeknikOzellikler { get; set; }
        public int Stok { get; set; }
        public Nullable<int> EkleyenUyeId { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<bool> Silik { get; set; }
        public Nullable<int> SilenUyeId { get; set; }
        public Nullable<System.DateTime> SilmeTarihi { get; set; }
        public Nullable<int> GuncelleyenUyeId { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
    
        public virtual TblKategoriler TblKategoriler { get; set; }
        public virtual TblMarka TblMarka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavori> TblFavori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSepet> TblSepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSiparisDetay> TblSiparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblYorum> TblYorum { get; set; }
    }
}
