//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUye()
        {
            this.TblUyeKisi = new HashSet<TblUyeKisi>();
            this.TblFavori = new HashSet<TblFavori>();
            this.TblSiparis = new HashSet<TblSiparis>();
            this.TblYorum = new HashSet<TblYorum>();
        }
    
        public int UyeId { get; set; }
        public string UyeMailAdresi { get; set; }
        public string Sifre { get; set; }
        public System.DateTime UyeKayitTarihi { get; set; }
        public Nullable<bool> Donuk { get; set; }
        public Nullable<System.DateTime> DondurmaTarihi { get; set; }
        public Nullable<bool> Silik { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public Nullable<bool> SifremiUnuttum { get; set; }
        public string SifirlamaKodu { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUyeKisi> TblUyeKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavori> TblFavori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSiparis> TblSiparis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblYorum> TblYorum { get; set; }
    }
}
