//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUyeKisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUyeKisi()
        {
            this.TblKisiAdres = new HashSet<TblKisiAdres>();
            this.TblKisiTelefon = new HashSet<TblKisiTelefon>();
        }
    
        public int KisiId { get; set; }
        public int UyeId { get; set; }
        public string KisiAd { get; set; }
        public string KisiSoyad { get; set; }
        public long KisiTc { get; set; }
        public Nullable<System.DateTime> KisiDogumTarihi { get; set; }
        public string KisiCinsiyet { get; set; }
        public Nullable<bool> Silik { get; set; }
    
        public virtual TblUye TblUye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKisiAdres> TblKisiAdres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKisiTelefon> TblKisiTelefon { get; set; }
    }
}
