//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYorum
    {
        public int YorumId { get; set; }
        public int UrunId { get; set; }
        public int UyeId { get; set; }
        public string YorumIcerik { get; set; }
        public System.DateTime YorumTarihi { get; set; }
        public bool Onaylandi { get; set; }
        public bool Silik { get; set; }
    
        public virtual TblUrun TblUrun { get; set; }
        public virtual TblUye TblUye { get; set; }
    }
}
