//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwKisiAdresTelefon
    {
        public int KisiId { get; set; }
        public int Expr1 { get; set; }
        public string AdresBaslik { get; set; }
        public string AdresUlke { get; set; }
        public string AdresIl { get; set; }
        public string AdresIlce { get; set; }
        public string Adres { get; set; }
        public string TelefonNumarasi { get; set; }
        public int AdresId { get; set; }
        public int TelefonId { get; set; }
        public Nullable<bool> FaturaAdresi { get; set; }
    }
}
