//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSiparisUrun
    {
        public int SiparisId { get; set; }
        public int UyeId { get; set; }
        public Nullable<int> AdresId { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public decimal ToplamTutar { get; set; }
        public bool OdemeDurumu { get; set; }
        public int UrunId { get; set; }
        public int KategoriId { get; set; }
        public int MarkaId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKodu { get; set; }
        public string UrunResimUrl { get; set; }
        public decimal UrunFiyat { get; set; }
        public string UrunAciklama { get; set; }
        public string TeknikOzellikler { get; set; }
        public int Stok { get; set; }
    }
}
