//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwUyeKisi
    {
        public int UyeId { get; set; }
        public int Expr1 { get; set; }
        public string UyeMailAdresi { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> Donuk { get; set; }
        public Nullable<System.DateTime> DondurmaTarihi { get; set; }
        public string KisiAd { get; set; }
        public string KisiSoyad { get; set; }
        public long KisiTc { get; set; }
        public Nullable<System.DateTime> KisiDogumTarihi { get; set; }
        public string KisiCinsiyet { get; set; }
        public System.DateTime UyeKayitTarihi { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Silik { get; set; }
        public Nullable<bool> Expr2 { get; set; }
    }
}
